[tool.pytest.ini_options]
markers = [
    "arm_demo: marks tests as arm_demo (deselect with '-m \"not arm_demo\"')",
]

[tool.flake8]
exclude = [
    "./inverse_kinematics/CCDIK/*",
    ".venv"
]
ignore = [
    "E128",
    "E501",
    "F403",
    "F405",
    "W293"
]